# Site
title:              Amal Shehu
bio:                'Software Engineer, Nerd and Hard Working Problem Solver. '
description:        "An intense desire to design and build applications as a full stack developer."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/back.jpg'
tiled_bg:           False   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                //amalshehu.github.io   

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   amalshehu-github-io

# Social
# if you don't have any of social below, comment the line.
google:
  plus:   AmalShehu
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              amalshehu@gmail.com
twitter:            amal_shehu
facebook:           amalshehu
github:             amalshehu
stackoverflow:      5832179/amal-shehu
linkedin:           amalshehu
#xing:              username
instagram:          amalshehu
#lastfm:            username
#tumblr:            username
#pinterest:          amalshehu
#foursquare:        username
steam:              amalshehu
#dribbble:          username
youtube:            amalshehu1
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
